//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class POSEntities : DbContext
    {
        public POSEntities()
            : base("name=POSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_Company> tbl_Company { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_Location> tbl_Location { get; set; }
        public virtual DbSet<tbl_LocationPrice> tbl_LocationPrice { get; set; }
        public virtual DbSet<tbl_Material> tbl_Material { get; set; }
        public virtual DbSet<tbl_MaterialEAN> tbl_MaterialEAN { get; set; }
        public virtual DbSet<tbl_PriceFile> tbl_PriceFile { get; set; }
        public virtual DbSet<tbl_Region> tbl_Region { get; set; }
        public virtual DbSet<tbl_Storage> tbl_Storage { get; set; }
        public virtual DbSet<tbl_Tender> tbl_Tender { get; set; }
        public virtual DbSet<tbl_Terminal> tbl_Terminal { get; set; }
        public virtual DbSet<tbl_Vendor> tbl_Vendor { get; set; }
    
        public virtual ObjectResult<Proc_GetAllLTerminal_Result> Proc_GetAllLTerminal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetAllLTerminal_Result>("Proc_GetAllLTerminal");
        }
    
        public virtual ObjectResult<Proc_GetMasterTerminal_Result> Proc_GetMasterTerminal(string locationID)
        {
            var locationIDParameter = locationID != null ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetMasterTerminal_Result>("Proc_GetMasterTerminal", locationIDParameter);
        }
    
        public virtual ObjectResult<Proc_LoadGetLocationStorage_Result> Proc_LoadGetLocationStorage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_LoadGetLocationStorage_Result>("Proc_LoadGetLocationStorage");
        }
    
        public virtual ObjectResult<Proc_LoadMasterTerminal_Result> Proc_LoadMasterTerminal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_LoadMasterTerminal_Result>("Proc_LoadMasterTerminal");
        }
    
        public virtual ObjectResult<Proc_LoadMasterVendor_Result> Proc_LoadMasterVendor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_LoadMasterVendor_Result>("Proc_LoadMasterVendor");
        }
    
        public virtual ObjectResult<Proc_LoadStorageGetById_Result> Proc_LoadStorageGetById(string locationId)
        {
            var locationIdParameter = locationId != null ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_LoadStorageGetById_Result>("Proc_LoadStorageGetById", locationIdParameter);
        }
    
        public virtual ObjectResult<Proc_GetMasterCategory_Result> Proc_GetMasterCategory(string categoryID)
        {
            var categoryIDParameter = categoryID != null ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetMasterCategory_Result>("Proc_GetMasterCategory", categoryIDParameter);
        }
    
        public virtual ObjectResult<Proc_LoadMasterLocation_Result> Proc_LoadMasterLocation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_LoadMasterLocation_Result>("Proc_LoadMasterLocation");
        }
    }
}
