//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tender
    {
        public string TenderID { get; set; }
        public string TenderName { get; set; }
        public string GL_Debit { get; set; }
        public string GL_Credit { get; set; }
    
        public virtual tbl_Tender tbl_Tender1 { get; set; }
        public virtual tbl_Tender tbl_Tender2 { get; set; }
    }
}
