//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_UOM()
        {
            this.tbl_Material = new HashSet<tbl_Material>();
            this.tbl_MaterialEAN = new HashSet<tbl_MaterialEAN>();
            this.tbl_MaterialEAN1 = new HashSet<tbl_MaterialEAN>();
            this.tbl_PriceFile = new HashSet<tbl_PriceFile>();
        }
    
        public string UOM { get; set; }
        public string UOMDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Material> tbl_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MaterialEAN> tbl_MaterialEAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MaterialEAN> tbl_MaterialEAN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PriceFile> tbl_PriceFile { get; set; }
        public virtual tbl_UOM tbl_UOM1 { get; set; }
        public virtual tbl_UOM tbl_UOM2 { get; set; }
    }
}
