//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Location()
        {
            this.tbl_Storage = new HashSet<tbl_Storage>();
            this.tbl_Terminal = new HashSet<tbl_Terminal>();
        }
    
        public string LocationID { get; set; }
        public string LocationDesc { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string POBox { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string CostCenter { get; set; }
        public string BusinessArea { get; set; }
        public string FieldArea { get; set; }
        public Nullable<decimal> CashLoan { get; set; }
        public Nullable<int> CustInt1 { get; set; }
        public Nullable<int> CustInt2 { get; set; }
        public Nullable<int> CustInt3 { get; set; }
        public string CustText1 { get; set; }
        public string CustText2 { get; set; }
        public string CustText3 { get; set; }
        public string TfrDisplay { get; set; }
        public string POReceive { get; set; }
        public string TfrIn { get; set; }
        public string TfrOut { get; set; }
        public string RtnVendor { get; set; }
        public string PhyCount { get; set; }
    
        public virtual tbl_City tbl_City { get; set; }
        public virtual tbl_Location tbl_Location1 { get; set; }
        public virtual tbl_Location tbl_Location2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Storage> tbl_Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Terminal> tbl_Terminal { get; set; }
    }
}
