//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Storage
    {
        public string StorageID { get; set; }
        public string StorageName { get; set; }
        public string StorageType { get; set; }
        public string LocationID { get; set; }
    
        public virtual tbl_Location tbl_Location { get; set; }
    }
}
