//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Entity.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PriceFile
    {
        public string EAN13 { get; set; }
        public string MaterialID { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual tbl_Material tbl_Material { get; set; }
        public virtual tbl_MaterialEAN tbl_MaterialEAN { get; set; }
        public virtual tbl_PriceFile tbl_PriceFile1 { get; set; }
        public virtual tbl_PriceFile tbl_PriceFile2 { get; set; }
    }
}
